import type { Identifier, ObjectPrettify, ObjectPrettifyDeep, Url } from "typeforge"

export type ThumbnailFormat = "Png" | "Jpeg" | "WebP"

export type ThumbnailReturnPolicy = "PlaceHolder" | "AutoGenerated" | "ForceAutoGenerated"


// [ GAMES ] /////////////////////////////////////////////////////////////////////////////////////////////////////////
export type GameThumbnailSize = "256x144" | "384x216" | "480x270" | "576x324" | "768x432"


// GET /v1/games/multiget/thumbnails ---------------------------------------------------------------------------------
type GamesThumbnailsData = ObjectPrettify<{
  error: null,
  thumbnails: {
    targetId: number,
    state:  "Completed" | "Pending" | "Error",
    imageUrl: Url,
    version: "TN2" | "TN3"
  }[]
} | {
  error: {
    code: number,
    message: string,
    userFacingMessage: string,
    field: string,
    fieldData: string
  },
  thumbnails: null
}>


export type RawGamesThumbnailsData<UniverseId extends Identifier> = ObjectPrettifyDeep<{
  data: ({ universeId: UniverseId } & GamesThumbnailsData)[]
}>

export type PrettifiedGamesThumbnailsData<UniverseId extends Identifier> = ObjectPrettifyDeep<{
  [Key in UniverseId]: GamesThumbnailsData
}>
// -------------------------------------------------------------------------------------------------------------------


// GET /v1/games/icons -----------------------------------------------------------------------------------------------
export type GamesIconSize = "50x50" | "128x128" | "150x150" | "256x256" | "512x512"

export type RawGamesIconsData<UniverseId extends Identifier> = ObjectPrettify<{
  data: {
    targetId: UniverseId,
    state:  "Completed" | "Pending" | "Error",
    imageUrl: string,
    version: "TN2" | "TN3"
  }[]
}>
export type PrettifiedGamesIconsData<UniverseId extends Identifier> = ObjectPrettify<{
  [Key in UniverseId]: {
    state: "Completed" | "Pending" | "Error",
    imageUrl: Url,
    version: "TN2" | "TN3"
  }
}>
// -------------------------------------------------------------------------------------------------------------------
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////